[package]

name = "wavefront_obj"
description = "A parser for the Wavefront .obj file format."
license = "MIT"
repository = "https://github.com/PistonDevelopers/wavefront_obj"
version = "2.0.2"
authors = [
    "Clark Gaebel <cg.wowus.cg@gmail.com>",
  ]
